# Generated by Django 5.2.7 on 2025-10-31 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFs', '0001_initial'),
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='linked_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.note'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
