# Generated by Django 5.2.7 on 2025-11-01 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFs', '0002_pdf_linked_note_alter_pdf_file'),
        ('notebook', '0002_note_notebook_no_owner_i_959e24_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['uploaded_by'], name='PDFs_pdf_uploade_666dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['is_public'], name='PDFs_pdf_is_publ_1f9b39_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['created_at'], name='PDFs_pdf_created_d01234_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['linked_note'], name='PDFs_pdf_linked__af20e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['uploaded_by', 'is_public'], name='PDFs_pdf_uploade_33b6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='PDFs_pdf_uploade_2dd1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['is_public', 'created_at'], name='PDFs_pdf_is_publ_1537c9_idx'),
        ),
    ]
