# Generated by Django 5.2.7 on 2025-11-01 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner'], name='notebook_no_owner_i_959e24_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['notebook'], name='notebook_no_noteboo_fb604d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_public'], name='notebook_no_is_publ_c59287_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_deleted'], name='notebook_no_is_dele_67f314_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='notebook_no_created_80b363_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['updated_at'], name='notebook_no_updated_cd565f_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'is_deleted'], name='notebook_no_owner_i_4fa906_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_public', 'is_deleted'], name='notebook_no_is_publ_6db3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'is_deleted', 'updated_at'], name='notebook_no_owner_i_e1bc58_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['owner'], name='notebook_no_owner_i_77d688_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['created_at'], name='notebook_no_created_68db96_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['owner', 'created_at'], name='notebook_no_owner_i_c38e78_idx'),
        ),
    ]
